from itertools import count

# fastapi is a framework for building apis with python
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

# in fast api the data is validated before it enters the code while mongo db can store garbage data silently and bugs may arise later 

app = FastAPI(title="Tasks API", version="1.0.0")
# app object 

#in python variable: type is a type hint way of telling 


# in express you write the code that checks the data 
# in fast api you write the description and the framework validates it 
class TaskCreate(BaseModel): 
     #basemodel is used to define schemas and validation rules and validate or convert data before entering the code
    title: str = Field(min_length=1, max_length=100, examples=["Learn FastAPI"]) 
    #no default value given so no fallback therefore this is required feild 
    #feild is extra rules on top  and 
    # examaples is for the autogenerated docs by fastapi using swagger ui for exampels nothing to do tieh logic
    completed: bool = False #if after = a value is given then its optional otherwise its not optional


class Task(TaskCreate):
    id: int


tasks: dict[int, Task] = {} #this is a dict in which key is int and value is task
#this is the temporary database
task_ids = count(1)


#tags is just for the docs page which tells group this route under health section
@app.get("/", tags=["health"])  #this is a decorator 
#decorator wraps a function with another function
def health_check() -> dict[str, str]:  #after -> is the data type which will be returned 
    return {"message": "Tasks API is running"}
# {"message": "Tasks API is running"} is the dict which has 2 strings 

@app.get("/tasks", response_model=list[Task], tags=["tasks"])
def list_tasks() -> list[Task]:  #Task is the model which hass all 3 feilds
    #list[Task] means a list containing task objects
    return list(tasks.values()) #this just gives you the task not the task no 

# response model tells what the response should look like when it is sent to the client
#  task_id is same as :id param
@app.get("/tasks/{task_id}", response_model=Task, tags=["tasks"])
def get_task(task_id: int) -> Task: #Task is the datatype of thing which will be returned
    task = tasks.get(task_id) 
    #using the task id we get in the request we get the task related and store it in task variable
    if task is None:
        # if task is not found we tell that the task does not exist
        raise HTTPException(status_code=404, detail="Task not found")
        #raise is used to raise a error
        #the detail is sent in the response.json sent to the client 
    return task

# if it works send the 201 in response code rather than the generic 
# status.HTTP_201_CREATED this is just a variable inside ststus module
@app.post("/tasks", response_model=Task, status_code=status.HTTP_201_CREATED, tags=["tasks"])
def create_task(task_data: TaskCreate) -> Task: #take the data the user sent and call it tas_data
    task = Task(id=next(task_ids), **task_data.model_dump())
    tasks[task.id] = task
    return task

# -> after this is just for humans and editors not for checking while respose_model is for checking if the output is actually correct


@app.put("/tasks/{task_id}", response_model=Task, tags=["tasks"])
#when certain data is sent by the client fastapi does some work on it turning that text into object
def update_task(task_id: int, task_data: TaskCreate) -> Task:
    if task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found")
    task = Task(id=task_id, **task_data.model_dump())  
    #so here we take the object task_data and model_dump says take this data and dump everything into the respective places
    # and then add the id on top of it
    #model dump is used to convert pydantic model into a dictniory
    tasks[task_id] = task
    return task


@app.delete("/tasks/{task_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["tasks"])
def delete_task(task_id: int) -> None:
    if task_id not in tasks:
        raise HTTPException(status_code=404, detail="Task not found")
    del tasks[task_id]
